source 'https://rubygems.org'

gem 'rails'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'govuk_frontend_toolkit', '0.43.2'
gem 'moj_template'
gem 'coffee-rails'
gem 'rspec-rails'
gem 'zendesk_api'
gem 'mail'

group :test, :development do
  gem 'rspec-rails'
  gem 'byebug'
  gem 'timecop'
  gem 'rubyzip'
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'curb'
  gem 'parallel'
  gem 'rspec_junit_formatter'
  gem 'poltergeist'
end
