source 'https://rubygems.org'

gem 'rails'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'govuk_frontend_toolkit', '1.5.0'
gem 'moj_template', '0.16.1'
gem 'coffee-rails'
gem 'zendesk_api'
gem 'mail'
gem 'elasticsearch'
gem 'logstasher'
gem 'sentry-raven'
gem 'redcarpet'
gem 'prison_staff_info', git: 'git@github.com:ministryofjustice/prison_staff_info.git', branch: 'master'
gem 'redis-rails'

group :test, :development do
  gem 'rspec-rails'
  gem 'byebug'
  gem 'timecop'
  gem 'rubyzip'
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'curb'
  gem 'parallel'
  gem 'rspec_junit_formatter'
  gem 'poltergeist'
  gem 'chromedriver-helper'
end
