source 'https://rubygems.org'

gem 'rails'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'govuk_frontend_toolkit', '1.3.0'
gem 'moj_template', '0.12.0'
gem 'coffee-rails'
gem 'rspec-rails'
gem 'zendesk_api'
gem 'mail'
gem 'elasticsearch'
gem 'logstasher', git: 'https://github.com/jasiek/logstasher.git', branch: 'action-mailer-custom-fields'
gem 'sentry-raven'

group :test, :development do
  gem 'rspec-rails'
  gem 'byebug'
  gem 'timecop'
  gem 'rubyzip'
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'curb'
  gem 'parallel'
  gem 'rspec_junit_formatter'
  gem 'poltergeist'
end
