---
name: Askham Grange
nomis_id: AGI
address:
- Askham Richard
- YO23 3FT
email: socialvisits.askhamgrange@hmps.gsi.gov.uk
enabled: true
estate: Askham Grange
phone: 
slots:
  sat:
  - 1345-1545
  sun:
  - 1345-1545
unbookable:
- 2014-12-25
- 2015-12-24
- 2015-12-25
- 2015-12-31
