---
name: Isle of Wight - Albany
nomis_id: ALI
address:
- 55 Parkhurst Road
- PO30 5RS
email: socialvisitsisleofwight@hmps.gsi.gov.uk
enabled: true
estate: Isle of Wight - Albany
phone: 01983 634218
slot_anomalies:
  2015-12-28:
  - 1400-1600
slots:
  fri:
  - 1400-1600
  mon:
  - 1400-1600
  sat:
  - 1400-1600
  sun:
  - 1400-1600
unbookable:
- 2014-12-25
- 2015-12-24
- 2015-12-25
- 2015-12-26
