---
name: Bullingdon (Convicted Only)
nomis_id: BNI
address:
- Bicester
- OX25 1PZ
email: socialvisits.bullingdon@hmps.gsi.gov.uk
enabled: true
finder_slug: bullingdon
phone: 01869 353176
slots:
  mon:
  - 1400-1610
  sat:
  - 1400-1610
  sun:
  - 1400-1610
  thu:
  - 1400-1610
  tue:
  - 1400-1610
  wed:
  - 1400-1610
unbookable:
- 2014-12-25
- 2014-12-26
