---
name: Coldingley
nomis_id: CLI
address:
- Shaftesbury Road
- GU24 9EX
email: socialvisits.coldingley@hmps.gsi.gov.uk
enabled: true
estate: Coldingley
phone: 01483 344418
slots:
  mon:
  - 1400-1545
  tue:
  - 1800-1900
  wed:
  - 1400-1545
  thu:
  - 1400-1545
  fri:
  - 1400-1545
  sat:
  - 1400-1545
  sun:
  - 0930-1100
  - 1400-1545
