---
name: Standford Hill
nomis_id: EHI
address:
- Church Road
- 'ME12 4AA '
canned_responses: true
email: socialvisits.standfordhill@hmps.gsi.gov.uk
enabled: true
estate: Standford Hill
finder_slug: sheppey-cluster-standford-hill
phone: 0300 060 6603
slots:
  wed:
  - 1345-1545
  sat:
  - 1345-1545
  sun:
  - 1345-1545
unbookable:
- 2014-12-25
