---
name: East Sutton Park
nomis_id: ESI
address:
- Sutton Valence
- Maidstone
- Kent
- ME17 3DF
email: socialvisits.eastsuttonpark@hmps.gsi.gov.uk
enabled: true
estate: East Sutton Park
phone: 01622 845010
slots:
  sat:
  - 1330-1530
  sun:
  - 1330-1530
