---
name: Frankland
nomis_id: FKI
enabled: true
estate: Frankland
address:
- Brasside
- Durham
- DH1 5YD
booking_window: 28
email: Frankland@hmps.gsi.gov.uk
lead_days: 3
phone: 01913 765048
slots:
  tue:
  - 1400-1600
  wed:
  - 1400-1600
  thu:
  - 1400-1600
  fri:
  - 1400-1600
  sat:
  - 1400-1600
  sun:
  - 1400-1600
unbookable:
- 2015-12-25
- 2015-12-26
- 2016-01-01
