---
name: Grendon
nomis_id: GNI
address:
- Grendon Underwood
- HP18 0TL
email: socialvisits.grendon@hmps.gsi.gov.uk
enabled: true
estate: Grendon
phone: ''
slots:
  sat:
  - 1345-1545
  sun:
  - 1345-1545
  wed:
  - 1400-1600
unbookable:
- 2014-12-25
