---
name: Haverigg
nomis_id: HVI
address:
- MILLOM
- 'LA18 4NA '
adult_age: 10
email: socialvisits.haverigg@hmps.gsi.gov.uk
enabled: true
estate: Haverigg
phone: 01229713016
slots:
  mon:
  - 1400-1545
  wed:
  - 1400-1545
  thu:
  - 1400-1545
  fri:
  - 1400-1545
  sat:
  - 1400-1545
  sun:
  - 1400-1545
unbookable:
- 2015-04-03
- 2015-12-25
- 2015-12-26
