---
name: Moorland Closed
nomis_id: MDI
address:
- Bawtry Road
- DN7 6BW
email: socialvisits.moorlandclosed@hmps.gsi.gov.uk
enabled: true
estate: Moorland Closed
finder_slug: moorland
lead_days: 1
phone: 01302523289
slots:
  wed:
  - 1340-1545
  thu:
  - 1340-1545
  sat:
  - 1340-1545
  sun:
  - 1340-1545
unbookable:
- 2014-12-25
- 2014-12-26
- 2015-01-01
