---
name: New Hall
nomis_id: NHI
address:
- Dial Wood
- WF4 4XX
canned_responses: true
email: socialvisits.newhall@hmps.gsi.gov.uk
enabled: true
phone: 01924 803219
slots:
  sat:
  - 1400-1600
  sun:
  - 1400-1600
  thu:
  - 1400-1600
  tue:
  - 1400-1600
  wed:
  - 1400-1600
unbookable:
- 2014-12-25
- 2014-12-26
- 2015-01-01
