---
name: Norwich (A, B, C, E, M only)
nomis_id: NWI
address:
- Knox Road
- 'NR1 4LU '
email: socialvisits.norwich@hmps.gsi.gov.uk
enabled: true
estate: Norwich
finder_slug: norwich
phone: 01603 708795
slots:
  tue:
  - 0930-1130
  wed:
  - 1415-1615
  thu:
  - 0930-1130
  sat:
  - 1415-1615
  sun:
  - 0930-1130
unbookable:
- 2014-12-25
- 2014-12-26
- 2015-12-25
- 2015-12-26
- 2016-01-01
