---
name: Winchester (Convicted only)
nomis_id: WCI
address:
- Romsey Road
- SO22 5DF
canned_responses: true
email: socialvisits.winchester@hmps.gsi.gov.uk
enabled: true
finder_slug: winchester
phone: 0845 223 5514
slots:
  fri:
  - 1400-1600
  mon:
  - 1400-1600
  sat:
  - 1400-1600
  sun:
  - 1400-1600
  thu:
  - 1400-1600
  tue:
  - 1400-1600
  wed:
  - 1400-1600
unbookable:
- 2014-12-25
- 2014-12-26
- 2015-04-03
